export const TODO_LIST = "TODO_LIST";
export const ADD_LIST = "ADD_LIST";
export const DELETE_LIST = "DELETE_LIST";
export const MODIFY_LIST = "MODIFY_LIST";

export const TODO_LIST_SUCCESS = "TODO_LIST_SUCCESS";
export const ADD_LIST_SUCCESS = "ADD_LIST_SUCCESS";
export const DELETE_LIST_SUCCESS = "DELETE_LIST_SUCCESS";
export const MODIFY_LIST_SUCCESS = "MODIFY_LIST_SUCCESS";
